# -*- coding: utf-8 -*-
"""Iris .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VDi0BlaHkTqwkvSr0pa1btaz6fs_xxiv
"""

from sklearn.datasets import load_iris
import pandas as pd

# Load dataset
iris = load_iris()

# Create a DataFrame
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target

# Map target values to species names
df['species'] = df['species'].map({i: species for i, species in enumerate(iris.target_names)})

df.head()

# @title species vs petal width (cm)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['species'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='petal width (cm)', y='species', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)





# @title species vs petal length (cm)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['species'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='petal length (cm)', y='species', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

# @title species vs sepal width (cm)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['species'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='sepal width (cm)', y='species', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

# @title species vs sepal length (cm)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['species'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='sepal length (cm)', y='species', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

# @title petal width (cm)

from matplotlib import pyplot as plt
df['petal width (cm)'].plot(kind='line', figsize=(8, 4), title='petal width (cm)')
plt.gca().spines[['top', 'right']].set_visible(False)

# @title petal length (cm)

from matplotlib import pyplot as plt
df['petal length (cm)'].plot(kind='line', figsize=(8, 4), title='petal length (cm)')
plt.gca().spines[['top', 'right']].set_visible(False)

# @title sepal width (cm)

from matplotlib import pyplot as plt
df['sepal width (cm)'].plot(kind='line', figsize=(8, 4), title='sepal width (cm)')
plt.gca().spines[['top', 'right']].set_visible(False)

# @title sepal length (cm)

from matplotlib import pyplot as plt
df['sepal length (cm)'].plot(kind='line', figsize=(8, 4), title='sepal length (cm)')
plt.gca().spines[['top', 'right']].set_visible(False)

# @title petal length (cm) vs petal width (cm)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='petal length (cm)', y='petal width (cm)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title sepal width (cm) vs petal length (cm)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='sepal width (cm)', y='petal length (cm)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title sepal length (cm) vs sepal width (cm)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='sepal length (cm)', y='sepal width (cm)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title species

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('species').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title petal width (cm)

from matplotlib import pyplot as plt
df['petal width (cm)'].plot(kind='hist', bins=20, title='petal width (cm)')
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title petal length (cm)

from matplotlib import pyplot as plt
df['petal length (cm)'].plot(kind='hist', bins=20, title='petal length (cm)')
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title sepal width (cm)

from matplotlib import pyplot as plt
df['sepal width (cm)'].plot(kind='hist', bins=20, title='sepal width (cm)')
plt.gca().spines[['top', 'right',]].set_visible(False)

import seaborn as sns
import matplotlib.pyplot as plt

# Pairplot for visualizing relationships
sns.pairplot(df, hue='species')
plt.show()

# Histograms
df.hist(figsize=(10, 6))
plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split

X = df[iris.feature_names]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print(X_train[:2])

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)
print(model)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))